/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  theme: {
    fontFamily: {
      // rubik: ["Rubik", "sans serif"],
    },
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".6rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
    listStyleType: {
      none: "none",
      disc: "disc",
      decimal: "decimal",
      square: "square",
      roman: "upper-roman",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#ffffff",
      black: "#000000",
      purple: "#3f3cbb",
      midnight: "#121063",
      metal: "#565584",
      tahiti: "#3ab7bf",
      silver: "#ecebff",
      "bubble-gum": "#ff77e9",
      bermuda: "#78dcca",
      mint: "#BCD8C1",
      blue: "#4a8fe7",
      red: "#FF8181",
      lightgrey: "#E5E5E5",
      dark: "#3A3335",
      grey: "#C4C4C4",
      purple: "#E5CBFF",
      "light-purple": "#F6F0FF",
      "light-blue": "#CDDFF5",
      "background-purple": "#F5EAFF",
      "background-mint": "#E6F2E8",
      "background-blue": "#EAF1FA",
      main: "#fa4002",
      blue: "#0439D9",
      blue2: "#074DD9",
    },
    extend: {
      spacing: {
        20: "80px",
        30: "120px",
        40: "160px",
        55: "220px",
        100: "1px",
        300: "1200px",
      },
    },
  },
  plugins: [],
};
